CREATE DATABASE tech0;
USE tech0;
CREATE TABLE news(id int, title varchar(255), contents text, posted datetime, author varchar(255), tags varchar(1000), PRIMARY KEY(id));
CREATE TABLE releases(id int, title varchar(255), release_code varchar(10), release_date datetime, artist varchar(100), has_cd varchar(3), PRIMARY KEY(id));
CREATE TABLE songs(song_id int, release_id int, release_song_id int, title varchar(255), duration time, PRIMARY KEY(song_id));
CREATE TABLE shows(id int, show_date datetime, continent varchar(50), country varchar(100), city varchar(100), venue varchar(100), other_bands text, band_comments text, setlist text, performers text, PRIMARY KEY(id));
CREATE TABLE news_comments(id int, comment_subid int, news_id int, author varchar(200), comment text, posted datetime, PRIMARY KEY(id));
CREATE TABLE release_comments(id int, comment_subid int, release_id int, author varchar(200), comment text, posted datetime, PRIMARY KEY(id));

INSERT INTO news VALUES(1, "News title", "News contents", "2016-01-01 00:00:00", "Juha", "Tag, Toinen");
INSERT INTO news VALUES(2, "Another news title", "More news contents", "2016-01-02 02:00:00", "Juha", "Tag, Test, Toinen");
INSERT INTO releases VALUES(1, "Debut Album", "CD001", "2010-04-04 00:00:00", "Artiste", "yes");
INSERT INTO releases VALUES(2, "Album 2: The Return", "CD002", "2012-04-05 00:00:00", "Artiste", "no");
INSERT INTO releases VALUES(3, "Album 3: Resurrection", "CD003", "2014-04-05 00:00:00", "Artiste", "yes");
INSERT INTO songs VALUES(1, 1, 1, "Song number 1", "00:03:16");
INSERT INTO songs VALUES(2, 1, 2, "Song number 2", "00:03:46");
INSERT INTO songs VALUES(3, 2, 1, "A new song", "00:06:16");
INSERT INTO songs VALUES(4, 3, 1, "Triple trouble", "00:04:26");
INSERT INTO songs VALUES(5, 3, 2, "Quadrouble", "00:04:56");
INSERT INTO shows VALUES(1, "2015-03-03 00:00:00", "Europe", "Finland", "Tornio", "Pikisaari", "Joku|www.testi.fi, Toinen|www.bandi.fi", "Nice show", "Eka|Toka|Kolmas", "Juha|Gtr, Mikko|Vox, Ville|Drums");
INSERT INTO shows VALUES(2, "2015-03-05 00:00:00", "Europe", "Finland", "Espoo", "Bodom", "Joku|www.testi.fi, Toinen|www.bandi.fi", "Nice show again", "Eka biisi|Toka|Kolmas", "Juha|Gtr, Mikko|Vox, Ville|Drums");
